# -*- mode: ruby -*-
# vi: set ft=ruby :
#Written by Brunet Geoffrey

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "postgresql"
  config.vm.network "private_network", type: "dhcp"
  config.vm.box_check_update = true
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
  end
end
