# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "jenkins"
  config.vm.network "public_network"
  config.vm.box_check_update = true

   config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
     vb.memory = "1024"
   end

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt update && sudo apt -y upgrade
     sudo add-apt-repository ppa:webupd8team/java
     sudo apt -y install oracle-java8-installer
     wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
     sudo apt-add-repository "deb https://pkg.jenkins.io/debian-stable binary/"
     sudo apt-add-repository "deb http://pkg.jenkins-ci.org/debian binary/"
     sudo apt install jenkins
     sudo cat /var/lib/jenkins/secrets/initialAdminPassword
   SHELL
end
