# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "jenkins"
  config.vm.network "private_network", type: "dhcp"
  config.vm.box_check_update = true
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "512"
     vb.cpus = 1
  end
end